import { Shield, Sparkles } from "lucide-react"

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background text-foreground pt-24 pb-16 relative overflow-hidden">
            {/* Background Ambience */}
            <div className="absolute inset-0 -z-10 overflow-hidden opacity-50">
                <div className="absolute top-1/2 left-1/4 w-[40rem] h-[40rem] bg-primary/5 rounded-full blur-[150px] mix-blend-screen" />
                <div className="absolute inset-0 bg-grid-gold/[0.02]" />
            </div>

            <div className="container mx-auto px-4 max-w-4xl relative z-10">
                <div className="mb-12">
                    <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-black/5 border border-black/5 text-primary text-sm font-medium mb-6">
                        <Shield className="h-4 w-4" />
                        Our Commitment
                    </div>
                    <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms of <span className="text-gradient">Service</span></h1>
                    <p className="text-xl text-muted-foreground">Effective Date: January 1, 2026</p>
                </div>

                <div className="space-y-12 text-muted-foreground leading-relaxed">
                    <section className="bg-black/5 p-8 rounded-2xl border border-black/5 glass-panel">
                        <h2 className="text-2xl font-bold text-foreground mb-4">1. Acceptance of Terms</h2>
                        <p>
                            By accessing GlowMark Aesthetics (&quot;Service&quot;), you agree to be bound by these Terms.
                            If you disagree with any part of the terms, please discontinue use immediately.
                            Our beauty platform strictly forbids unauthorized data collection or misuse of the analysis tools.
                        </p>
                    </section>

                    <section className="bg-black/5 p-8 rounded-2xl border border-black/5 glass-panel">
                        <h2 className="text-2xl font-bold text-foreground mb-4">2. Photo Analysis Usage</h2>
                        <p className="mb-4">
                            Our platform analyzes facial proportions for aesthetic purposes. We assert that:
                        </p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>All beauty scores (Symmetry, Proportion, Harmony) are estimates generated by software.</li>
                            <li>GlowMark does not provide medical diagnoses or professional cosmetic surgery advice.</li>
                            <li>Images uploaded to our platform are temporary and instantly deleted after your session.</li>
                        </ul>
                    </section>

                    <section className="bg-black/5 p-8 rounded-2xl border border-black/5 glass-panel">
                        <h2 className="text-2xl font-bold text-foreground mb-4">3. Prohibited Conduct</h2>
                        <p>
                            You may not use the GlowMark platform to analyze subjects without their explicit consent,
                            reverse-engineer the beauty analysis models, or attempt to upload malicious files
                            into the photo analysis tool.
                        </p>
                    </section>

                </div>
            </div>
        </div>
    )
}
